### ISSUE TITLE
Multiple frameworks / cross compile

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#190]
The work involved here is:
- [x] Cross targeting: Projects can build from the command line #380 
- [x] Cross targeting: Projects open in VS with an active TFM #383 
- [x] Cross targeting: Projects have combined intellisense #384 
- [x] Cross targeting: Projects can build all TFMs from VS #504
- [x] Cross targeting: P2P references to and from a cross-targeting project #385

**Comment by davkean** [comment]
Lots of complexity here, still early at the moment to really figure this out. Do we just model this via configurations? Or something built-in to msbuild?

**Comment by onovotny** [comment]
@davkean I hope it's far more elegant than configurations - unless it's hidden. I'm assuming that by Configurations, you mean Debug and Release (by default). I would not want to add a x-compile as more configs, instead I would want Debug/Release to apply to all my x-compiled outputs.

P2P refs would need to know what the best matching output is based on the TFM resolution rules as it can get complex.

**Comment by davkean** [comment]
By "configurations" here, I'm talking about how we represent it behind the scenes in the project system, not how it's exposed to developers.

**Comment by gulbanana** [comment]
this feature will enable something like Shared Projects, but with app-model-specific functions (for example shared projects don't support .resx). from the point of view of xproj it's parity but for csproj (and vbproj?) it will be a pretty nice step forward!
