### ISSUE TITLE
Stop stripping whitespace

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#512]
We should react this to this MSBuild change in CPS: https://github.com/Microsoft/msbuild/pull/1036#issuecomment-249942381

- [ ] Make sure we don't remove blank line at end of file
- [ ] Make sure we don't remove byte order mark
- [ ] Make sure we don't reformat comments
- [ ] Make sure we don't stip whitespace

**Comment by srivatsn** [comment]
Should this be filed in the CPR repo?

**Comment by davkean** [comment]
I like to have a tracking but on our side.

**Comment by davkean** [comment]
We haven't reacted to this?

**Comment by 333fred** [comment]
Some of the work for this is done, but there's still a CPS change needed. It won't be in for RC3.

**Comment by 333fred** [comment]
Fixed with #1266.
